version: 1
accounts:
  - name: alice
    coins: ['20000token', '200000000stake']
  - name: bob
    coins: ['10000token', '100000000stake']
    address: charlie14uhk9ueggndqsc9pz6a4qrlkks3wpz0945dkkt
validators:
  - name: alice
    bonded: '100000000stake'
client:
  openapi:
    path: 'docs/static/openapi.yml'
  typescript:
    path: 'ts-client'
  vuex:
    path: 'vue/src/store'
faucet:
  name: bob
  coins: ['5token', '100000stake']
